name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
    - name: setup
      shell: bash -l {0}
      run: conda install --yes --quiet -c bioconda -c conda-forge nextflow procps-ng
    - name: test
      shell: bash -l {0}
      run: | 
        ./main.nf --help
        ./main.nf -profile conda --wget --accession_list=tests/wget.txt --out_dir="results" -c tests/test.conf
        test -f results/S10_L001_I1_001.fastq.gz
        ./main.nf -profile conda --sra --accession_list=tests/sra.txt --out_dir="results" -c tests/test.conf
        test -f results/SRR4216351.fastq.gz
